CREATE TABLE IF NOT EXISTS page_embeddings (     page_id INTEGER PRIMARY KEY REFERENCES pages(id) ON DELETE CASCADE,     dim     INTEGER,     vec     BLOB );
CREATE TABLE IF NOT EXISTS doc_summaries (doc_id INTEGER PRIMARY KEY, summary TEXT, topics TEXT);
CREATE TABLE IF NOT EXISTS persona_cache (id INTEGER PRIMARY KEY CHECK(id=1), data TEXT, built_at TEXT);
CREATE TABLE IF NOT EXISTS users (username TEXT PRIMARY KEY, salt TEXT, pwd TEXT, created TEXT, pv INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS personas (username TEXT PRIMARY KEY, data TEXT, mbti TEXT, emb BLOB);
CREATE TABLE IF NOT EXISTS friends (owner TEXT, friend TEXT, PRIMARY KEY(owner,friend));
CREATE TABLE IF NOT EXISTS match_cache (owner TEXT, other TEXT, data TEXT, PRIMARY KEY(owner,other));
CREATE TABLE IF NOT EXISTS life_cache (username TEXT PRIMARY KEY, data TEXT);
CREATE TABLE IF NOT EXISTS users2 (phone TEXT PRIMARY KEY, nickname TEXT, created TEXT, gender TEXT, age TEXT, zodiac TEXT, mbti TEXT, bio TEXT, pwd TEXT, pv INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS sms_codes (phone TEXT PRIMARY KEY, code TEXT, exp INTEGER);
CREATE TABLE IF NOT EXISTS avatars (username TEXT PRIMARY KEY, dataurl TEXT);
CREATE TABLE IF NOT EXISTS card_msgs (id INTEGER PRIMARY KEY, card_id INTEGER, content TEXT, created TEXT, read INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS today_cache (username TEXT PRIMARY KEY, day TEXT, data TEXT);
CREATE TABLE IF NOT EXISTS card_status (card_id INTEGER PRIMARY KEY, status TEXT);
CREATE TABLE IF NOT EXISTS friendships (owner TEXT, friend TEXT, created TEXT, PRIMARY KEY(owner,friend));
CREATE TABLE IF NOT EXISTS doc_connections (doc_id INTEGER PRIMARY KEY, data TEXT);
CREATE TABLE IF NOT EXISTS song_cache (username TEXT PRIMARY KEY, data TEXT);
CREATE TABLE IF NOT EXISTS media_structure (doc_id INTEGER PRIMARY KEY, data TEXT);
CREATE TABLE IF NOT EXISTS links_cache (username TEXT PRIMARY KEY, day TEXT, data TEXT);
CREATE TABLE IF NOT EXISTS news_cache (username TEXT PRIMARY KEY, day TEXT, data TEXT);
CREATE TABLE IF NOT EXISTS kb_entities (     id INTEGER PRIMARY KEY,     doc_id INTEGER NOT NULL,     owner TEXT,     name TEXT NOT NULL,     norm TEXT NOT NULL,     etype TEXT,     mentions INTEGER DEFAULT 1 );
CREATE TABLE IF NOT EXISTS relationship_cards (     username TEXT,     contact  TEXT,     doc_id   INTEGER,     day      TEXT,     msgcount INTEGER,     data     TEXT,     PRIMARY KEY (username, contact) );
CREATE TABLE IF NOT EXISTS chat_intel (     username TEXT,     contact  TEXT,     doc_id   INTEGER,     msgcount INTEGER,     day      TEXT,     data     TEXT,     PRIMARY KEY (username, contact) );
CREATE TABLE IF NOT EXISTS ingest_progress( owner TEXT, job_id TEXT, contact TEXT, state TEXT, percent INTEGER, message TEXT, ts REAL, PRIMARY KEY(owner, job_id, contact));
CREATE TABLE IF NOT EXISTS realtime_state( owner TEXT PRIMARY KEY, enabled INTEGER DEFAULT 0, running INTEGER DEFAULT 0, pending INTEGER DEFAULT 0, last_synced TEXT, last_beat_ts REAL, note TEXT);
CREATE TABLE IF NOT EXISTS wechat_seen(owner TEXT, msg_id TEXT, PRIMARY KEY(owner,msg_id));
CREATE TABLE IF NOT EXISTS wechat_lines(owner TEXT, fp TEXT, PRIMARY KEY(owner,fp));
CREATE TABLE IF NOT EXISTS portrait_cache(owner TEXT PRIMARY KEY, day TEXT, data TEXT);
CREATE TABLE IF NOT EXISTS card_hidden(username TEXT, contact TEXT, PRIMARY KEY(username,contact));
CREATE TABLE IF NOT EXISTS analysis_processed(owner TEXT, layer TEXT, doc_id INTEGER, PRIMARY KEY(owner,layer,doc_id));
CREATE TABLE IF NOT EXISTS doc_kind(owner TEXT, doc_id INTEGER, is_group INTEGER, last_date TEXT, PRIMARY KEY(owner,doc_id));
CREATE TABLE IF NOT EXISTS commit_dismissed(username TEXT, key TEXT, ts TEXT, PRIMARY KEY(username,key));
CREATE TABLE IF NOT EXISTS loop_dismissed(username TEXT, key TEXT, PRIMARY KEY(username,key));
CREATE TABLE IF NOT EXISTS reach_dismissed(username TEXT, contact TEXT, PRIMARY KEY(username,contact));
CREATE TABLE IF NOT EXISTS relation_timeline_cache(owner TEXT, doc_id INTEGER, pages INTEGER, data TEXT, PRIMARY KEY(owner,doc_id));
CREATE TABLE IF NOT EXISTS group_graph_cache(owner TEXT, doc_id INTEGER, pages INTEGER, data TEXT, PRIMARY KEY(owner,doc_id));
CREATE TABLE IF NOT EXISTS matches_cache(username TEXT, sig TEXT, data TEXT, PRIMARY KEY(username,sig));
CREATE TABLE IF NOT EXISTS chat_topic_names(owner TEXT, k INTEGER, sig TEXT, names TEXT, PRIMARY KEY(owner,k));
CREATE TABLE IF NOT EXISTS conn_explain(owner TEXT, key TEXT, data TEXT, day TEXT, PRIMARY KEY(owner,key));
CREATE TABLE IF NOT EXISTS ask_cache(owner TEXT, k TEXT, day TEXT, data TEXT, PRIMARY KEY(owner,k));
CREATE TABLE IF NOT EXISTS compute_cache(owner TEXT, name TEXT, sig TEXT, data TEXT, PRIMARY KEY(owner,name));
CREATE TABLE IF NOT EXISTS insights_cache(owner TEXT, name TEXT, sig TEXT, data TEXT, PRIMARY KEY(owner,name));
CREATE TABLE IF NOT EXISTS gen_cache(owner TEXT, k TEXT, day TEXT, data TEXT, PRIMARY KEY(owner,k));
CREATE TABLE IF NOT EXISTS library_topics_cache (k TEXT PRIMARY KEY, sig TEXT, data TEXT, built_at TEXT);
CREATE TABLE IF NOT EXISTS song_ledger (username TEXT, month TEXT, style TEXT, voice TEXT, bpm TEXT, need TEXT, title TEXT, PRIMARY KEY(username, month));
